import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {newCampaign,prepareCreation,preview,backup,parseBackup,summary,clone} from '../dist/core.js';
import {previewUpdate} from '../dist/updates.js';
import {dayToken,verifyToken,DAY_COUNT,planAdvance,safeDisplay,visibleEvents,thresholdProgress,createScheduler} from '../dist/progress.js';
import {assertAutomatable,consumeUpdateReview,protectedOperations} from '../dist/operation-policy.js';
const seed=()=>prepareCreation(newCampaign({display_name:'Scheduler test',resources:[{id:'health',label:'Health'}],ability_slots_enabled:true}),'Opening').next;
const op=(s,op,props={},reason='Test')=>({op,character_id:s.characters[0].character_id,reason,...props});
const packet=(s,operations,update_id=crypto.randomUUID())=>({format:'scroll-session-update',version:1,campaign_id:s.campaign_id,lineage_id:s.lineage_id,base_revision:s.current_revision,update_id,operations});
const event=(s,day)=>op(s,'schedule_event',{visibility:'dm_only',eligible_from_day:day,must_fire_by_day:day,selection_rule:'first_day'},'created');
function clearCover(s){s.scheduler.cover='0'.repeat(DAY_COUNT);}
function coverAt(s,days){const a=Array.from(s.scheduler.cover);for(const d of days)a[d]='1';s.scheduler.cover=a.join('');}
test('creation and legacy upgrade use full-range generator with independent frozen cover',()=>{const s=seed();assert.equal(s.scheduler.stream.length,DAY_COUNT*8);assert.equal(s.scheduler.cover.length,DAY_COUNT);const n=[...s.scheduler.cover].filter(v=>v==='1').length;assert.ok(n>31000&&n<35500);assert.ok(verifyToken(s,dayToken(s,0)));assert.ok(verifyToken(s,dayToken(s,DAY_COUNT-1)));assert.equal(verifyToken(s,dayToken(s).slice(0,-1)+'Z'),false);const legacy=clone(s);delete legacy.scheduler;delete legacy.thresholds;legacy.current_day=73;const up=preview(legacy,[{op:'activate_scheduler'}],'Upgrade').next;assert.equal(up.scheduler.stream.length,s.scheduler.stream.length);assert.equal(up.scheduler.cover.length,s.scheduler.cover.length);assert.ok(verifyToken(up,dayToken(up,0)));assert.ok(verifyToken(up,dayToken(up,DAY_COUNT-1)));assert.equal(dayToken(parseBackup(JSON.stringify(backup(up))).state),dayToken(up));});
test('first real or cover stop commits once, remainder resumes and positions vary',()=>{let s=seed();clearCover(s);coverAt(s,[5,12]);s=previewUpdate(s,packet(s,[event(s,9)])).next;let p=previewUpdate(s,packet(s,[{op:'advance_day',to_day:20,reason:'Travel'}]));assert.equal(p.next.current_day,5);assert.equal(p.next.scheduler.remainder.target_day,20);assert.equal(p.receipt.day_tokens.length,4);assert.equal(visibleEvents(p.next).length,0);s=p.next;p=preview(s,[{op:'advance_day',to_day:s.scheduler.remainder.target_day}],'Resume');assert.equal(p.next.current_day,9);assert.equal(visibleEvents(p.next).length,1);s=p.next;p=preview(s,[{op:'advance_day',to_day:20}],'Resume');assert.equal(p.next.current_day,12);assert.equal(visibleEvents(p.next).length,1);s=p.next;p=preview(s,[{op:'advance_day',to_day:20}],'Resume');assert.equal(p.next.current_day,20);assert.equal(p.next.scheduler.remainder,null);});
test('untraveled and unscoped effects are held while time commits, retry cannot reapply',()=>{const s=seed();clearCover(s);coverAt(s,[4]);const u=packet(s,[op(s,'award_xp',{delta:50,effective_day:10}),{op:'advance_day',to_day:10,reason:'Travel'}],'journey');const p=previewUpdate(s,u);assert.equal(p.next.current_day,4);assert.equal(p.next.characters[0].xp_total,0);assert.equal(p.receipt.status,'interrupted');assert.equal(p.receipt.interruption.day_reached,4);assert.equal(p.next.transactions.at(-1).operations.length,1);assert.equal(previewUpdate(p.next,u).status,'already_applied');assert.deepEqual(parseBackup(JSON.stringify(backup(p.next))).state,p.next);const q=previewUpdate(s,packet(s,[op(s,'award_xp',{delta:50}),{op:'advance_day',to_day:10,reason:'Travel'}]));assert.equal(q.next.characters[0].xp_total,0);});
test('effects explicitly scoped through reached day apply with elapsed time only',()=>{const s=seed();clearCover(s);coverAt(s,[4]);const p=previewUpdate(s,packet(s,[op(s,'award_xp',{delta:3,effective_day:4}),{op:'advance_day',to_day:10,reason:'Travel'}]));assert.equal(p.next.current_day,4);assert.equal(p.next.characters[0].xp_total,3);assert.equal(p.receipt.status,'applied');});
test('invalid held operations reject entire request without even advancing time',()=>{const s=seed();clearCover(s);coverAt(s,[3]);assert.throws(()=>previewUpdate(s,packet(s,[op(s,'set_xp',{value:-1,effective_day:7}),{op:'advance_day',to_day:7,reason:'Travel'}])));assert.equal(s.current_day,1);});
test('sessions, rewinds and summaries do not fire or un-fire events; unresolved persist',()=>{let s=seed();clearCover(s);s=previewUpdate(s,packet(s,[event(s,3)])).next;s=preview(s,[{op:'open_session'}],'Open').next;assert.equal(visibleEvents(s).length,0);assert.equal(JSON.parse(summary(s)).unresolved_events.length,0);s=preview(s,[{op:'advance_day',to_day:3}],'Travel').next;s=preview(s,[{op:'close_session'}],'Close').next;s=preview(s,[{op:'correct_day',to_day:1}],'Correction').next;assert.equal(visibleEvents(s).length,1);assert.equal(s.sessions[0].advance_submitted,true);const e=visibleEvents(s)[0];const p=previewUpdate(s,packet(s,[op(s,'resolve_event',{event_id:e.id},'resolved')]));assert.equal(visibleEvents(p.next).length,0);assert.ok(protectedOperations(p.next.transactions.at(-1).operations).length);assert.throws(()=>consumeUpdateReview(p),/human review/);});
test('hidden schedule dates never appear in summary, safe backup or safe journal projection',()=>{let s=seed();s=previewUpdate(s,packet(s,[event(s,54321)])).next;const projected=JSON.stringify(safeDisplay(backup(s)));assert.ok(!projected.includes('54321'));assert.ok(!summary(s).includes('54321'));assert.ok(!projected.includes('fires_on_day'));assert.ok(!projected.includes(s.scheduler.stream));assert.throws(()=>previewUpdate(s,packet(s,[{...event(s,50000),label:'Forbidden'}])));assert.throws(()=>previewUpdate(s,packet(s,[{...event(s,50000),reason:'descriptive prose'}])));});
test('absolute reconciliation, thresholds and required attribute note remain literal',()=>{const s=seed();s.characters[0].attributes=[{key:'might',label:'Might',value:16,note:'+3'}];const p=previewUpdate(s,packet(s,[op(s,'set_xp',{value:44}),op(s,'set_currency',{value:-2}),op(s,'set_level_threshold',{level:9,cumulative_xp:3000}),op(s,'set_attribute',{key:'might',value:18,note:'+4'})]));assert.equal(p.next.characters[0].xp_total,44);assert.equal(p.next.characters[0].currency_amount,-2);assert.equal(p.next.level_thresholds['9'],3000);assert.equal(p.next.characters[0].attributes[0].note,'+4');assert.throws(()=>previewUpdate(s,packet(s,[op(s,'set_attribute',{key:'might',value:18})])));});
function training(s){s.thresholds=[{id:'learn',character_id:s.characters[0].character_id,label:'Learn',completed_on_day:null,stages:[{stage_index:0,required:3,baseline:{successes:2,streak:0,note:'Migrated'},consecutive_required:false,dc_revisions:[{revision_id:'d1',dc:17,set_on_day:1}],attempts:[]},{stage_index:1,required:2,baseline:{successes:0,streak:0,note:''},consecutive_required:true,dc_revisions:[{revision_id:'d2',dc:20,set_on_day:1}],attempts:[]}]}];return s;}
test('external attempts preserve migrated 2/3, stage order, failure streak and completion',()=>{let s=training(seed());const attempt=(result,stage_index)=>op(s,'log_threshold_attempt',{threshold_id:'learn',stage_index,result,dc_revision_id:stage_index?'d2':'d1'});assert.throws(()=>previewUpdate(s,packet(s,[attempt('success',1)])));s=previewUpdate(s,packet(s,[attempt('success',0)])).next;assert.equal(thresholdProgress(s.thresholds[0]).current_stage_index,1);for(const result of ['success','failure','success','success'])s=previewUpdate(s,packet(s,[attempt(result,1)])).next;assert.equal(thresholdProgress(s.thresholds[0]).complete,true);assert.equal(s.thresholds[0].stages[1].attempts.length,4);assert.throws(()=>previewUpdate(s,packet(s,[attempt('success',1)])));});
test('ability status is explicit and independent; open slots accept mid-session details',()=>{const s=training(seed());s.characters[0].ability_slots=[{index:1,name:null,applications:[]}];assert.throws(()=>previewUpdate(s,packet(s,[op(s,'set_ability_detail',{slot_index:1,application_name:'Art',cost:'None'})])));let p=previewUpdate(s,packet(s,[op(s,'set_ability_detail',{slot_index:1,application_name:'Art',status:'trained_unquantified',cost:'None'})]));assert.equal(p.next.characters[0].ability_slots[0].applications[0].status,'trained_unquantified');assert.equal(p.next.characters[0].ability_slots[0].applications[0].effect,'not yet quantified');assert.throws(()=>previewUpdate(s,packet(s,[op(s,'set_ability_detail',{slot_index:1,application_name:'Art',status:'in_development'})])));p=previewUpdate(s,packet(s,[op(s,'set_ability_detail',{slot_index:1,application_name:'Art',status:'in_development',threshold_id:'learn'})]));assert.equal(p.next.characters[0].ability_slots[0].applications[0].threshold_id,'learn');});

test('sequential resource diffs preserve independent current and maximum values',()=>{const s=seed();const p=previewUpdate(s,packet(s,[op(s,'set_resource_max',{resource:'health',value:45}),op(s,'adjust_resource',{resource:'health',delta:51})]));const diffs=p.diffs.filter(d=>d.field==='resources');assert.equal(diffs[0].to[0].current,0);assert.equal(diffs[1].from[0].current,0);assert.equal(diffs[1].to[0].current,51);assert.equal(p.next.characters[0].resources[0].max,45);});

test('manual travel handoff includes every crossed day token',()=>{const s=seed();clearCover(s);const p=preview(s,[{op:'advance_day',to_day:5}],'Travel');const handoff=JSON.parse(summary(p.next));assert.equal(handoff.last_advance_tokens.length,4);assert.equal(handoff.last_advance_tokens.at(-1),dayToken(p.next));});
