import {assertAutomatable} from '../dist/operation-policy.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {newCampaign,prepareCreation,clone,backup,parseBackup,summary} from '../dist/core.js';
import {previewUpdate,parseUpdate} from '../dist/updates.js';
function fixture(){const s=newCampaign({display_name:'Level test',resources:[{id:'health',label:'Health'},{id:'energy',label:'Energy'}]});const c=s.characters[0];c.level=7;c.xp_total=2000;c.resources=[{id:'health',current:20,max:45},{id:'energy',current:10,max:18}];c.attributes=[{key:'agility',label:'Agility',value:16,note:'+3'},{key:'presence',label:'Presence',value:18}];return prepareCreation(s,'Test').next;}
const operation=(s,op,args)=>({op,character_id:s.characters[0].character_id,reason:'Level-up confirmed by DM',...args});
const envelope=(s,operations)=>({format:'scroll-session-update',version:1,campaign_id:s.campaign_id,lineage_id:s.lineage_id,update_id:'level-up',base_revision:s.current_revision,operations});
test('level-up changes two maxima, level and two attributes in one atomic reviewed batch',()=>{const s=fixture(),u=envelope(s,[operation(s,'set_resource_max',{resource:'health',value:52}),operation(s,'set_resource_max',{resource:'energy',value:21}),operation(s,'set_level',{value:8}),operation(s,'set_attribute',{key:'agility',value:18,note:'+4'}),operation(s,'set_attribute',{key:'presence',value:19,note:''})]);const p=previewUpdate(s,u),c=p.next.characters[0];assert.equal(s.characters[0].level,7);assert.equal(c.level,8);assert.equal(c.xp_total,2000);assert.deepEqual(c.resources,[{id:'health',current:20,max:52},{id:'energy',current:10,max:21}]);assert.deepEqual(c.attributes,[{key:'agility',label:'Agility',value:18,note:'+4'},{key:'presence',label:'Presence',value:19,note:''}]);assert.equal(c.reference_revision,2);assert.equal(p.next.current_revision,s.current_revision+1);assert.ok(p.receipt.confirmed_changes.some(d=>d.field==='attributes'));assert.equal(new Set(p.next.journal.slice(s.journal.length).map(j=>j.transaction_id)).size,1);assert.deepEqual(parseBackup(JSON.stringify(backup(p.next))).state,p.next);assert.equal(previewUpdate(p.next,u).status,'already_applied');});
test('maximum updates neither heal nor clamp even when lowered below current',()=>{const s=fixture(),p=previewUpdate(s,envelope(s,[operation(s,'set_resource_max',{resource:'health',value:0})]));assert.equal(p.next.characters[0].resources[0].current,20);assert.equal(p.next.characters[0].resources[0].max,0);assert.equal(p.next.characters[0].reference_revision,0);});
test('current resource restoration requires a separate explicit delta',()=>{const s=fixture(),p=previewUpdate(s,envelope(s,[operation(s,'set_resource_max',{resource:'health',value:52}),operation(s,'adjust_resource',{resource:'health',delta:32})]));assert.equal(p.next.characters[0].resources[0].current,52);assert.equal(p.next.characters[0].resources[0].max,52);});
test('absolute operations require value and reject delta, missing character IDs, invalid bounds and types',()=>{const s=fixture();for(const op of ['set_resource_max','set_level','set_attribute']){const args=op==='set_resource_max'?{resource:'health',value:52}:op==='set_attribute'?{key:'agility',value:18,note:'+3'}:{value:8};let o=operation(s,op,args);delete o.character_id;assert.throws(()=>previewUpdate(s,envelope(s,[o])));o=operation(s,op,{...args,delta:1});assert.throws(()=>parseUpdate(JSON.stringify(envelope(s,[o]))));o=operation(s,op,args);delete o.value;assert.throws(()=>previewUpdate(s,envelope(s,[o])));}for(const [op,args]of [['set_level',{value:0}],['set_level',{value:1.5}],['set_resource_max',{resource:'health',value:-1}],['set_resource_max',{resource:'health',value:'52'}],['set_attribute',{key:'agility',value:true}]])assert.throws(()=>previewUpdate(s,envelope(s,[operation(s,op,args)])));});
test('unknown attribute, resource or character rejects the whole level-up',()=>{const s=fixture(),before=clone(s);for(const o of [operation(s,'set_attribute',{key:'typo',value:18}),operation(s,'set_resource_max',{resource:'typo',value:52}),{...operation(s,'set_level',{value:8}),character_id:'other'}])assert.throws(()=>previewUpdate(s,envelope(s,[operation(s,'set_level',{value:8}),o])));assert.deepEqual(s,before);});
test('attribute notes stay literal; explicit note updates or clears are supported',()=>{const s=fixture();let p=previewUpdate(s,envelope(s,[operation(s,'set_attribute',{key:'agility',value:18,note:'+3'})]));assert.equal(p.next.characters[0].attributes[0].note,'+3');p=previewUpdate(s,envelope(s,[operation(s,'set_attribute',{key:'agility',value:16,note:''})]));assert.equal(p.next.characters[0].attributes[0].note,'');assert.equal(p.next.characters[0].reference_revision,1);});
test('unchanged attributes do not dirty reference data; changed values stay out of routine summary',()=>{const s=fixture(),p=previewUpdate(s,envelope(s,[operation(s,'set_attribute',{key:'agility',value:16,note:'+3'}),operation(s,'set_level',{value:8})]));assert.equal(p.next.characters[0].reference_revision,0);assert.equal(JSON.parse(summary(p.next)).characters[0].attributes,undefined);});
test('new operations do not weaken protected DC or journal boundary',()=>{const s=fixture();for(const op of ['set_dc','record_roll','amend_event_date','resolve_event','edit_journal'])assert.throws(()=>assertAutomatable([operation(s,'set_level',{value:8}),{op,reason:'Override'}]),e=>e.code==='HUMAN_CONFIRMATION_REQUIRED');});
