import {newCampaign,prepareCreation} from '../dist/core.js';
import {createRequire} from 'node:module';import {readFile,writeFile,mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';const require=createRequire(import.meta.url),{webkit,chromium,devices}=require(process.env.SCROLL_PLAYWRIGHT_MODULE||'playwright');
const origin='http://127.0.0.1:4191',out=process.env.SCROLL_UPDATE_EVIDENCE||'update-ready-evidence';await mkdir(out+'/captures',{recursive:true});const fixture=prepareCreation(newCampaign({display_name:'Update audit',character_name:'Example owner',resources:[{id:'hp',label:'HP'}]}),'Synthetic opening').next,results=[];
for(const engine of ['chrome','webkit']){const browser=await(engine==='chrome'?chromium.launch({channel:'chrome',headless:true}):webkit.launch({headless:true})),context=await browser.newContext({...devices['iPhone 13'],viewport:{width:390,height:844}}),page=await context.newPage();let navigations=0;page.on('framenavigated',f=>{if(f===page.mainFrame())navigations++;});const row={engine,version:browser.version()};
try{await page.goto(origin);await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.locator('.build-label').waitFor();await page.evaluate(async s=>{const db=await new Promise((res,rej)=>{const r=indexedDB.open('scroll',2);r.onsuccess=()=>res(r.result);r.onerror=rej;});await new Promise((res,rej)=>{const t=db.transaction(['campaigns','preferences'],'readwrite');t.objectStore('campaigns').put(s);t.objectStore('preferences').put({key:'exchange:'+s.campaign_id+':'+s.lineage_id,value:{revision:s.current_revision,copied_state:true,copied_instructions:true,update_id:null,receipt_pasted:false,handoff_visited:false,handoff_copied:false,handoff_checked:false}});t.oncomplete=res;t.onabort=rej;});db.close();},fixture);await page.reload();await page.locator('.nav [data-tab="updates"]').click();const u={format:'scroll-session-update',version:1,campaign_id:fixture.campaign_id,lineage_id:fixture.lineage_id,base_revision:fixture.current_revision,update_id:'update-panel-test',operations:[{op:'adjust_currency',character_id:fixture.characters[0].character_id,delta:1,reason:'Synthetic preview, never saved'}]};await page.locator('#update-text').fill(JSON.stringify(u));await page.locator('[data-action="review-import"]').click();await page.locator('#confirm-save').waitFor();const initial=await page.locator('.build-label').innerText(),before=navigations;await page.evaluate(async()=>{await fetch('/__next',{method:'POST'});await(await navigator.serviceWorker.getRegistration()).update();});await page.locator('.update-ready').waitFor({state:'visible'});const button=page.locator('.update-ready button');await page.waitForFunction(()=>document.querySelector('.update-ready button').disabled);await page.waitForTimeout(700);assert.equal(navigations,before);assert.equal(await page.locator('#modal').evaluate(e=>e.open),true);assert.equal(await page.evaluate(async()=>(await navigator.serviceWorker.getRegistration()).waiting.state),'installed');await page.screenshot({path:out+'/captures/'+engine+'-preview-blocked.png',scale:'css'});row.previewBlocked=true;
await page.locator('#modal [data-close]').first().click();await page.waitForTimeout(300);assert.equal(await button.isDisabled(),true);assert.equal(navigations,before);row.draftBlocked=true;await page.locator('#update-text').fill('');await page.waitForFunction(()=>!document.querySelector('.update-ready button').disabled);
await page.locator('.nav [data-tab="play"]').click();await page.locator('[data-action="numbers"]').click();await page.locator('input[name="xp"]').fill('2');await page.waitForFunction(()=>document.querySelector('.update-ready button').disabled);assert.equal(navigations,before);row.formBlocked=true;await page.screenshot({path:out+'/captures/'+engine+'-form-blocked.png',scale:'css'});page.once('dialog',d=>d.accept());await page.locator('#modal [data-close]').first().click();await page.waitForFunction(()=>!document.querySelector('.update-ready button').disabled);
const other=await context.newPage();await other.goto(origin+'/snapshot.html');await other.locator('.build-label').waitFor();await button.click();await page.getByText('Close other Scroll windows, including the snapshot viewer, then try again.').waitFor();assert.equal(navigations,before);await page.screenshot({path:out+'/captures/'+engine+'-other-window-blocked.png',scale:'css'});row.otherWindowBlocked=true;await other.close();await button.click();await page.waitForFunction(old=>document.querySelector('.build-label')?.textContent!==old,initial);await page.locator('.build-label').waitFor();assert.equal(navigations,before+1);row.explicitSafeReloads=1;row.beforeBuild=initial;row.afterBuild=await page.locator('.build-label').innerText();await page.waitForTimeout(300);assert.equal(await page.locator('.update-ready').isVisible(),false);row.panelGoneOnNewBuild=true;
// A controller change not requested by this page must leave an open preview untouched.
await page.locator('.nav [data-tab="updates"]').click();await page.locator('#update-text').fill(JSON.stringify(u));await page.locator('[data-action="review-import"]').click();await page.locator('#confirm-save').waitFor();const stable=navigations;await page.evaluate(async()=>{await fetch('/__next',{method:'POST'});const registration=await navigator.serviceWorker.getRegistration();await registration.update();const worker=await new Promise((resolve,reject)=>{const start=Date.now();const poll=()=>{if(registration.waiting?.state==='installed')return resolve(registration.waiting);if(Date.now()-start>15000)return reject(Error('No installed worker'));setTimeout(poll,50);};poll();});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('No controller change')),10000);navigator.serviceWorker.addEventListener('controllerchange',()=>{clearTimeout(timer);resolve();},{once:true});const channel=new MessageChannel();worker.postMessage({type:'SCROLL_ACTIVATE'},[channel.port2]);});});await page.waitForTimeout(400);assert.equal(navigations,stable);assert.equal(await page.locator('#modal').evaluate(e=>e.open),true);row.externalControllerChangeKeptPreview=true;
await page.screenshot({path:out+'/captures/'+engine+'-updated.png',scale:'css'});row.passed=true;
}catch(e){row.passed=false;row.error=e.stack;await page.screenshot({path:out+'/captures/'+engine+'-failure.png',scale:'css'}).catch(()=>{});}results.push(row);await browser.close();}
await writeFile(out+'/update-ready-browser.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));if(results.some(r=>!r.passed))process.exitCode=1;
