import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';import {readFile,writeFile,mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{webkit,devices}=require(process.env.SCROLL_PLAYWRIGHT_MODULE||'playwright');
const out=process.env.SCROLL_AUDIT_OUTPUT||'warm-evidence',origin='http://127.0.0.1:4189';await mkdir(out+'/captures',{recursive:true});
const browser=await webkit.launch({headless:true}),results={engine:'Playwright WebKit',version:browser.version(),device:'iPhone 13; touch; 390x844; scale 3',physicalPhone:false,captures:[],taps:[],contrast:[]};
async function setup(mode='plain',olive=false){const context=await browser.newContext({...devices['iPhone 13'],viewport:{width:390,height:844}});await context.addInitScript(()=>{window.auditTouches=[];for(const type of ['touchstart','touchend'])document.addEventListener(type,e=>window.auditTouches.push({type,target:e.target.className}),{passive:true});});if(olive)await context.route('**/palette.css',r=>r.fulfill({contentType:'text/css',path:fileURLToPath(new URL('./fixtures/palette-olive.css',import.meta.url))}));const page=await context.newPage();await page.goto(origin+'/audit.html');await page.locator('[data-mode="'+mode+'"]').evaluate(b=>b.click());await page.waitForURL(mode.startsWith('snapshot')?'**/snapshot.html':origin+'/');await page.locator('.build-label').waitFor();return {page,context};}
async function save(page,name){await page.locator('#toast').waitFor({state:'hidden'}).catch(()=>{});await page.screenshot({path:out+'/captures/'+name+'.png',fullPage:true,scale:'css'});await writeFile(out+'/captures/'+name+'.txt',await page.locator('body').innerText());await page.screenshot({path:out+'/captures/'+name+'-viewport.png',scale:'css'});results.captures.push({name,build:await page.locator('.build-label').innerText(),width:await page.evaluate(()=>innerWidth),scrollWidth:await page.evaluate(()=>document.documentElement.scrollWidth)});results.contrast.push(...await page.evaluate(()=>{const samples=[];for(const el of document.querySelectorAll('body *')){if(!el.getClientRects().length||!Array.from(el.childNodes).some(n=>n.nodeType===3&&n.textContent.trim()))continue;const c=getComputedStyle(el);if(c.visibility==='hidden')continue;let node=el,bg;while(node){bg=getComputedStyle(node).backgroundColor;if(bg!=='rgba(0, 0, 0, 0)'&&bg!=='transparent')break;node=node.parentElement;}samples.push({selector:el.tagName.toLowerCase()+'.'+el.className,color:c.color,background:bg,fontSize:c.fontSize,text:el.textContent.trim().slice(0,65)});}return samples;}));}
async function close(page){await page.locator('#modal [data-close]').first().tap();}
async function copy(page,action){await page.locator('[data-action="'+action+'"]').first().tap();await page.locator('#copy-button').tap();if(await page.locator('#copy-button').textContent()==='I copied this block')await page.locator('#copy-button').tap();await close(page);}
const {page,context}=await setup();
await save(page,'moss-play-390');assert.equal(await page.locator('.nav [data-tab="updates"] .attention-dot').count(),0);
await page.locator('.nav [data-tab="updates"]').tap();await save(page,'moss-updates-fresh-390');assert.equal(await page.locator('#update-text').count(),0);assert.equal(await page.locator('.exchange-step button:disabled').count(),0);
await copy(page,'summary');assert.equal(await page.locator('.nav [data-tab="updates"] .attention-dot').count(),1);assert.match(await page.locator('#exchange-step-0').innerText(),/✓ State copied/);await copy(page,'dm-guide');await page.locator('#update-text').waitFor();await save(page,'moss-updates-copied-390');
const fixture=JSON.parse(await readFile(out+'/fixture.json','utf8'));const update={format:'scroll-session-update',version:1,campaign_id:fixture.campaign_id,lineage_id:fixture.lineage_id,base_revision:fixture.current_revision,update_id:'warm-ui-audit',operations:[{op:'adjust_currency',character_id:fixture.characters[0].character_id,delta:1,reason:'Synthetic visual audit'}]};
await page.locator('#update-text').fill(JSON.stringify(update));await page.locator('[data-action="review-import"]').tap();await page.locator('#confirm-save').waitFor();await save(page,'moss-import-preview-390');assert.equal(await page.locator('[data-approve-index]').count(),0);await page.locator('#confirm-save').tap();await page.getByRole('heading',{name:'Update saved · receipt for DM'}).waitFor();await close(page);await save(page,'moss-updates-saved-390');assert.equal(await page.locator('#exchange-step-2 [data-exchange-open]').getAttribute('aria-expanded'),'true');
await copy(page,'exchange-receipt');await page.locator('[data-action="exchange-pasted"]').tap();await page.locator('[data-action="exchange-handoff"]').tap();await page.locator('.nav [data-tab="updates"]').tap();await page.locator('[data-action="exchange-finish"]').tap();assert.match(await page.locator('.exchange-complete').innerText(),/All done/);assert.equal(await page.locator('.nav [data-tab="updates"] .attention-dot').count(),0);await save(page,'moss-updates-done-390');results.exchange='copy both → paste JSON → review dialog → save → copy receipt → manually acknowledge paste → visit handoff → manually confirm; all assertions passed';
for(const tab of ['play','updates','reference','roster','journal','backup']){await page.locator('.nav [data-tab="'+tab+'"]').tap();assert.equal(await page.locator('.nav .active').count(),1);const colors=await page.locator('.nav button').evaluateAll(buttons=>buttons.map(b=>({tab:b.dataset.tab,active:b.classList.contains('active'),background:getComputedStyle(b).backgroundColor})));const selected=colors.find(c=>c.active).background;assert.ok(colors.filter(c=>!c.active).every(c=>c.background!==selected));results.taps.push({tab,colors});await save(page,'moss-tab-'+tab+'-390');}
await page.locator('.nav [data-tab="reference"]').tap();await save(page,'moss-character-collapsed-390');
const details=page.locator('.ability-display').first(),preview=details.locator('.effect-preview');
results.tapSuspects=await preview.evaluate(el=>{const r=el.getBoundingClientRect(),c=getComputedStyle(el),summary=getComputedStyle(el.closest('summary'));return {clamp:c.webkitLineClamp,pointerEvents:c.pointerEvents,summaryTouchAction:summary.touchAction,summaryUserSelect:summary.webkitUserSelect,hit:document.elementFromPoint(r.left+10,r.top+5)?.outerHTML?.slice(0,200)};});
await preview.tap();assert.equal(await details.evaluate(el=>el.open),true);await save(page,'moss-character-expanded-390');
// Existing interactive control inside a move card must not collapse it.
await page.locator('.nav [data-tab="roster"]').tap();const move=page.locator('.move-display').first();await move.locator('summary').tap();assert.equal(await move.evaluate(el=>el.open),true);await move.locator('[data-action="roster-pp"]').tap();assert.equal(await move.evaluate(el=>el.open),true);await close(page);results.previewTapExpanded=true;results.interactiveButtonKeptOpen=true;
for(const width of [320,390]){await page.setViewportSize({width,height:844});await page.screenshot({path:out+'/captures/after-tabs-'+width+'.png',scale:'css'});const rects=await page.locator('.nav button').evaluateAll(bs=>bs.map(b=>({label:b.textContent.trim(),x:b.getBoundingClientRect().x,width:b.getBoundingClientRect().width,height:b.getBoundingClientRect().height,overflow:getComputedStyle(b.querySelector('span')).textOverflow})));assert.equal(rects.length,6);assert.ok(rects.every(r=>r.x>=0&&r.x+r.width<=width+1&&r.height>=44));results['nav'+width]=rects;}
results.touchEvents=await page.evaluate(()=>window.auditTouches);await context.close();
for(const mode of ['chain','snapshot','snapshot-hide']){const p=await setup(mode);await save(p.page,'moss-'+mode+'-390');await p.context.close();}
const o=await setup('plain',true);await save(o.page,'olive-play-390');await o.page.locator('.nav [data-tab="updates"]').tap();await save(o.page,'olive-updates-fresh-390');await o.page.locator('.nav [data-tab="reference"]').tap();await save(o.page,'olive-character-390');await o.context.close();
await writeFile(out+'/webkit-audit.json',JSON.stringify(results,null,2));await browser.close();console.log(JSON.stringify({...results,contrast:results.contrast.length+' text samples',touchEvents:results.touchEvents.length+' actual touchstart/end events'},null,2));
